#!/bin/bash
#
# Addendum to zshrc config
#
# Install by sourcing this file in your `~/.zshrc` file: `source path/to/this/file`
#


#
# oh-my-zsh setup
#
if [ ! -d "$HOME/.oh-my-zsh" ]
then
    echo "Installing oh-my-zsh"
    wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    sh install.sh --keep-zshrc
    rm -f isntall.sh
fi
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
# Uncomment the following line to display red dots whilst waiting for completion.
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
COMPLETION_WAITING_DOTS="true"
plugins=(git macos python)
source $ZSH/oh-my-zsh.sh


#
# More aliases
#
alias hn="hostname"
alias mem-by-proc="ps -v -u `whoami`"

#
# Remote sync
#
if [ -d "$HOME/opt/remote-sycn" ]
then
    export PATH=$PATH:$HOME/opt/remote-sync/bin
fi

